name: Deploy

on:
  push:
    paths:
      - prisma/index.ts
      - src/**
    branches: ["uat"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ca-central-1
  PROJECT: atlas

jobs:
  get-next-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release
        id: next-version
        uses: ./.github/actions/release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
    outputs:
      new-release-published: ${{ steps.next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.next-version.outputs.new-release-version }}
      new-release-git-tag: ${{ steps.next-version.outputs.new-release-git-tag }}

  build:
    needs: get-next-version
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'uat' }}
    env:
      REGISTRY: ${{ vars.ACCOUNT_ID }}.dkr.ecr.ca-central-1.amazonaws.com
      REPOSITORY: ${{ vars.ACCOUNT_ID }}.dkr.ecr.ca-central-1.amazonaws.com/atlas/api
      TAG: ${{ needs.get-next-version.outputs.new-release-version || github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_ARN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REPOSITORY }}
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.REPOSITORY }}/cache
          cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=${{ env.REPOSITORY }}/cache
    outputs:
      image: ${{ steps.meta.outputs.tags }}

  publish:
    needs: [build]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'uat' }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_ARN }}

      - name: Render Amazon ECS task definition
        id: render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-family: atlas-ecs-task
          container-name: api
          image: ${{ needs.build.outputs.image }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          desired-count: 1
          task-definition: ${{ steps.render-web-container.outputs.task-definition }}
          service: ${{ env.PROJECT }}-ecs-service
          cluster: ${{ env.PROJECT }}-cluster
          wait-for-service-stability: true

  release:
    needs: publish
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: ${{ success() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release
        id: next-version
        uses: ./.github/actions/release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
